// FarmMart seed data — farmers, products, and image mapping

export const PRODUCT_IMAGES: Record<string, string> = {
  basmati_rice: "/products/basmati_rice.jpg",
  wheat: "https://sfile.chatglm.cn/images-ppt/7a04c9892b1e.jpeg",
  corn: "https://sfile.chatglm.cn/images-ppt/89a7de5f271f.jpg",
  tomatoes: "https://sfile.chatglm.cn/images-ppt/4011b141dec9.jpg",
  onions: "https://sfile.chatglm.cn/images-ppt/3656a286bf4f.jpeg",
  potatoes: "https://sfile.chatglm.cn/images-ppt/35b359f135d6.jpg",
  spinach: "https://sfile.chatglm.cn/images-ppt/79797a0340dc.jpg",
  mango: "https://sfile.chatglm.cn/images-ppt/dd259948f0cf.jpg",
  pomegranate: "https://sfile.chatglm.cn/images-ppt/7256e0ae66be.jpg",
  banana: "https://sfile.chatglm.cn/images-ppt/1adbbf65c640.jpg",
  toor_dal: "https://sfile.chatglm.cn/images-ppt/69745e68aa23.jpeg",
  chickpeas: "https://sfile.chatglm.cn/images-ppt/e27c9607c397.jpg",
  turmeric: "https://sfile.chatglm.cn/images-ppt/3d0f4faae394.jpg",
  cardamom: "https://sfile.chatglm.cn/images-ppt/518fc92d3cc7.jpg",
  milk: "/products/milk.jpg",
  paneer: "https://sfile.chatglm.cn/images-ppt/15be9a030907.jpg",
  almonds: "https://sfile.chatglm.cn/images-ppt/2f199b3ef558.jpg",
  cashews: "https://sfile.chatglm.cn/images-ppt/1cb66221e400.jpg",
  basil: "https://sfile.chatglm.cn/images-ppt/64e8d023d867.jpg",
  mint: "https://sfile.chatglm.cn/images-ppt/4528fbf00a40.jpg",
};

export interface SeedUser {
  id: string;
  email: string;
  name: string;
  role: string;
  phone?: string;
  location: string;
  avatar: string | null;
  rating: number;
}

export const SEED_USERS: SeedUser[] = [
  {
    id: "u_buyer_demo",
    email: "buyer@farmmart.io",
    name: "Aarav Mehta",
    role: "BUYER",
    phone: "+91 98200 11223",
    location: "Pune, Maharashtra",
    avatar: null,
    rating: 5,
  },
  {
    id: "u_farmer_ravi",
    email: "ravi@farmmart.io",
    name: "Ravi Sharma",
    role: "FARMER",
    phone: "+91 99100 44556",
    location: "Nashik, Maharashtra",
    avatar: null,
    rating: 4.8,
  },
  {
    id: "u_farmer_meena",
    email: "meena@farmmart.io",
    name: "Meena Devi",
    role: "FARMER",
    phone: "+91 90040 77881",
    location: "Karnal, Haryana",
    avatar: null,
    rating: 4.9,
  },
  {
    id: "u_farmer_arjun",
    email: "arjun@farmmart.io",
    name: "Arjun Reddy",
    role: "FARMER",
    phone: "+91 98490 33221",
    location: "Hyderabad, Telangana",
    avatar: null,
    rating: 4.7,
  },
  {
    id: "u_farmer_sunita",
    email: "sunita@farmmart.io",
    name: "Sunita Patel",
    role: "FARMER",
    phone: "+91 97250 66112",
    location: "Anand, Gujarat",
    avatar: null,
    rating: 4.9,
  },
  {
    id: "u_farmer_jaswant",
    email: "jaswant@farmmart.io",
    name: "Jaswant Singh",
    role: "FARMER",
    phone: "+91 98150 22091",
    location: "Ludhiana, Punjab",
    avatar: null,
    rating: 4.8,
  },
  {
    id: "u_wholesale_global",
    email: "bulk@farmmart.io",
    name: "Global Traders Co.",
    role: "WHOLESALER",
    phone: "+91 99000 11100",
    location: "Mumbai, Maharashtra",
    avatar: null,
    rating: 4.6,
  },
  {
    id: "u_transport_fast",
    email: "fleet@farmmart.io",
    name: "FastTrack Logistics",
    role: "TRANSPORTER",
    phone: "+91 98888 00012",
    location: "Nagpur, Maharashtra",
    avatar: null,
    rating: 4.7,
  },
];

export interface SeedProduct {
  key: string; // image key
  name: string;
  category: string;
  description: string;
  price: number;
  unit: string;
  stock: number;
  location: string;
  organic: boolean;
  harvestDate: string;
  tags: string;
  rating: number;
  reviewCount: number;
  sold: number;
  farmerEmail: string;
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    key: "basmati_rice",
    name: "Premium Aged Basmati Rice",
    category: "Grains",
    description:
      "Aged for 24 months for elongated grains and rich aroma. Sourced directly from the foothills of the Himalayas. Ideal for biryani and pulao. Uniform grain length, low breakage, and a distinctly nutty flavor.",
    price: 95,
    unit: "kg",
    stock: 1800,
    location: "Karnal, Haryana",
    organic: false,
    harvestDate: "2025-04",
    tags: "aged,aromatic,premium,biryani",
    rating: 4.8,
    reviewCount: 142,
    sold: 5400,
    farmerEmail: "meena@farmmart.io",
  },
  {
    key: "wheat",
    name: "Golden Wheat (Sharbati)",
    category: "Grains",
    description:
      "Sharbati wheat from the Sehore region, known for its golden grain and high protein content. Stone-milled flour makes soft, fluffy rotis. Naturally sun-dried, no chemical treatment.",
    price: 32,
    unit: "kg",
    stock: 3200,
    location: "Ludhiana, Punjab",
    organic: false,
    harvestDate: "2025-04",
    tags: "sharbati,high-protein,roti",
    rating: 4.6,
    reviewCount: 98,
    sold: 8200,
    farmerEmail: "jaswant@farmmart.io",
  },
  {
    key: "corn",
    name: "Sweet Yellow Corn",
    category: "Grains",
    description:
      "Freshly harvested hybrid yellow corn with high moisture and sweet kernels. Suitable for human consumption, poultry feed, and starch extraction. Graded and cleaned.",
    price: 22,
    unit: "kg",
    stock: 2500,
    location: "Ludhiana, Punjab",
    organic: false,
    harvestDate: "2025-05",
    tags: "sweet,hybrid,feed",
    rating: 4.4,
    reviewCount: 56,
    sold: 3100,
    farmerEmail: "jaswant@farmmart.io",
  },
  {
    key: "tomatoes",
    name: "Organic Vine Tomatoes",
    category: "Vegetables",
    description:
      "Plump, juicy tomatoes ripened on the vine for maximum flavor. Grown organically without synthetic pesticides. Perfect for sauces, salads, and curries.",
    price: 40,
    unit: "kg",
    stock: 600,
    location: "Nashik, Maharashtra",
    organic: true,
    harvestDate: "2025-05",
    tags: "organic,vine-ripened,juicy",
    rating: 4.7,
    reviewCount: 73,
    sold: 1450,
    farmerEmail: "ravi@farmmart.io",
  },
  {
    key: "onions",
    name: "Red Onions (Nashik)",
    category: "Vegetables",
    description:
      "Pungent, shelf-stable red onions from the Nashik belt. Medium to large bulb size, low moisture loss. Graded and packed in mesh bags for ventilation.",
    price: 28,
    unit: "kg",
    stock: 4500,
    location: "Nashik, Maharashtra",
    organic: false,
    harvestDate: "2025-04",
    tags: "pungent,shelf-stable,graded",
    rating: 4.5,
    reviewCount: 120,
    sold: 9800,
    farmerEmail: "ravi@farmmart.io",
  },
  {
    key: "potatoes",
    name: "Potatoes (Chipsona)",
    category: "Vegetables",
    description:
      "Chipsona variety potatoes with low sugar content — ideal for chips and fries. Uniform size, smooth skin, disease-free. Cold-stored for year-round availability.",
    price: 24,
    unit: "kg",
    stock: 5200,
    location: "Karnal, Haryana",
    organic: false,
    harvestDate: "2025-03",
    tags: "chipsona,low-sugar,cold-stored",
    rating: 4.4,
    reviewCount: 64,
    sold: 6700,
    farmerEmail: "meena@farmmart.io",
  },
  {
    key: "spinach",
    name: "Organic Baby Spinach",
    category: "Vegetables",
    description:
      "Tender baby spinach leaves, harvested early for sweetness. Triple-washed and hydro-cooled. Rich in iron and vitamins. Best consumed within 4 days.",
    price: 45,
    unit: "kg",
    stock: 180,
    location: "Anand, Gujarat",
    organic: true,
    harvestDate: "2025-05",
    tags: "organic,baby-leaf,iron-rich",
    rating: 4.6,
    reviewCount: 38,
    sold: 620,
    farmerEmail: "sunita@farmmart.io",
  },
  {
    key: "mango",
    name: "Alphonso Mangoes (Devgad)",
    category: "Fruits",
    description:
      "Authentic Devgad Alphonso (Hapus) mangoes — the king of fruits. Naturally ripened without calcium carbide. Saffron-colored pulp, intense aroma, and negligible fiber.",
    price: 480,
    unit: "dozen",
    stock: 240,
    location: "Hyderabad, Telangana",
    organic: false,
    harvestDate: "2025-05",
    tags: "alphonso,hapus,premium,devgad",
    rating: 4.9,
    reviewCount: 211,
    sold: 1800,
    farmerEmail: "arjun@farmmart.io",
  },
  {
    key: "pomegranate",
    name: "Bhagwa Pomegranates",
    category: "Fruits",
    description:
      "Bhagwa variety — soft seeds, deep-red arils, and a sweet-tart balance. High juice content and long shelf life. Graded by size and hand-packed.",
    price: 140,
    unit: "kg",
    stock: 850,
    location: "Hyderabad, Telangana",
    organic: false,
    harvestDate: "2025-04",
    tags: "bhagwa,soft-seed,juicy",
    rating: 4.7,
    reviewCount: 89,
    sold: 2600,
    farmerEmail: "arjun@farmmart.io",
  },
  {
    key: "banana",
    name: "Cavendish Bananas",
    category: "Fruits",
    description:
      "Export-grade Cavendish bananas, uniform ripeness and blemish-free. Harvested at mature-green stage and ethylene-ripened for the perfect color. Rich in potassium.",
    price: 60,
    unit: "dozen",
    stock: 700,
    location: "Anand, Gujarat",
    organic: false,
    harvestDate: "2025-05",
    tags: "cavendish,export-grade,potassium",
    rating: 4.5,
    reviewCount: 51,
    sold: 3300,
    farmerEmail: "sunita@farmmart.io",
  },
  {
    key: "toor_dal",
    name: "Toor Dal (Pigeon Pea)",
    category: "Pulses",
    description:
      "Unpolished toor dal retaining natural protein and fiber. No artificial polishing agents. Splits cook evenly and yield a thick, creamy dal.",
    price: 120,
    unit: "kg",
    stock: 1400,
    location: "Karnal, Haryana",
    organic: false,
    harvestDate: "2025-02",
    tags: "unpolished,protein,creamy",
    rating: 4.6,
    reviewCount: 77,
    sold: 4200,
    farmerEmail: "meena@farmmart.io",
  },
  {
    key: "chickpeas",
    name: "Kabuli Chickpeas (Large)",
    category: "Pulses",
    description:
      "Grade-A Kabuli chickpeas — large, creamy-white, and uniform. High protein and low moisture. Ideal for chana, hummus, and snacks.",
    price: 95,
    unit: "kg",
    stock: 1900,
    location: "Ludhiana, Punjab",
    organic: false,
    harvestDate: "2025-03",
    tags: "kabuli,grade-a,protein",
    rating: 4.5,
    reviewCount: 43,
    sold: 2400,
    farmerEmail: "jaswant@farmmart.io",
  },
  {
    key: "turmeric",
    name: "Erode Turmeric (Whole & Powder)",
    category: "Spices",
    description:
      "High-curcumin Erode turmeric, sun-dried and stone-ground. Deep orange color and earthy aroma. Lab-tested for purity and pesticide residue.",
    price: 220,
    unit: "kg",
    stock: 480,
    location: "Hyderabad, Telangana",
    organic: true,
    harvestDate: "2025-01",
    tags: "high-curcumin,organic,erode",
    rating: 4.8,
    reviewCount: 65,
    sold: 1500,
    farmerEmail: "arjun@farmmart.io",
  },
  {
    key: "cardamom",
    name: "Green Cardamom (8mm)",
    category: "Spices",
    description:
      "Bold 8mm green cardamom from Idukki. Hand-picked, sun-cured, and steam-sterilized. Intense aroma with high volatile oil — premium export grade.",
    price: 1850,
    unit: "kg",
    stock: 95,
    location: "Anand, Gujarat",
    organic: false,
    harvestDate: "2025-02",
    tags: "bold,8mm,export-grade",
    rating: 4.9,
    reviewCount: 34,
    sold: 320,
    farmerEmail: "sunita@farmmart.io",
  },
  {
    key: "milk",
    name: "Fresh Cow Milk (A2)",
    category: "Dairy",
    description:
      "Pure A2 desi cow milk from grass-fed Gir cattle. Unadulterated, full-cream, chilled within 30 minutes of milking. Bottled in food-grade glass.",
    price: 70,
    unit: "litre",
    stock: 320,
    location: "Anand, Gujarat",
    organic: true,
    harvestDate: "2025-05",
    tags: "a2,gir-cow,full-cream",
    rating: 4.8,
    reviewCount: 92,
    sold: 5600,
    farmerEmail: "sunita@farmmart.io",
  },
  {
    key: "paneer",
    name: "Fresh Paneer (Hand-pressed)",
    category: "Dairy",
    description:
      "Soft, creamy paneer made from A2 milk using natural citric coagulation. Hand-pressed to retain moisture. No preservatives — best within 5 days.",
    price: 320,
    unit: "kg",
    stock: 150,
    location: "Anand, Gujarat",
    organic: true,
    harvestDate: "2025-05",
    tags: "fresh,a2-milk,soft",
    rating: 4.7,
    reviewCount: 58,
    sold: 1100,
    farmerEmail: "sunita@farmmart.io",
  },
  {
    key: "almonds",
    name: "California Almonds (Natural)",
    category: "Nuts",
    description:
      "Premium natural almonds, uniform size and crunchy texture. Rich in vitamin E and healthy fats. Sun-dried and sorted for shell fragments.",
    price: 720,
    unit: "kg",
    stock: 600,
    location: "Karnal, Haryana",
    organic: false,
    harvestDate: "2025-01",
    tags: "natural,vitamin-e,crunchy",
    rating: 4.6,
    reviewCount: 47,
    sold: 1900,
    farmerEmail: "meena@farmmart.io",
  },
  {
    key: "cashews",
    name: "Goa Cashews (W240)",
    category: "Nuts",
    description:
      "W240 grade whole cashews from Goa plantations. Creamy white, uniform, and free from blemishes. Lightly dried to retain natural sweetness.",
    price: 880,
    unit: "kg",
    stock: 420,
    location: "Anand, Gujarat",
    organic: false,
    harvestDate: "2025-02",
    tags: "w240,whole,creamy",
    rating: 4.7,
    reviewCount: 39,
    sold: 1450,
    farmerEmail: "sunita@farmmart.io",
  },
  {
    key: "basil",
    name: "Fresh Sweet Basil",
    category: "Herbs",
    description:
      "Aromatic sweet basil bunches, hydroponically grown for consistent flavor. Perfect for pesto and Italian dishes. Harvested to order for peak freshness.",
    price: 90,
    unit: "kg",
    stock: 80,
    location: "Nashik, Maharashtra",
    organic: true,
    harvestDate: "2025-05",
    tags: "sweet,hydroponic,aromatic",
    rating: 4.5,
    reviewCount: 22,
    sold: 280,
    farmerEmail: "ravi@farmmart.io",
  },
  {
    key: "mint",
    name: "Fresh Mint Leaves",
    category: "Herbs",
    description:
      "Cooling, fragrant mint leaves, bunch-packed with stems intact. Great for chutneys, teas, and garnishes. Hydro-cooled to preserve freshness.",
    price: 55,
    unit: "kg",
    stock: 110,
    location: "Nashik, Maharashtra",
    organic: true,
    harvestDate: "2025-05",
    tags: "cooling,fragrant,organic",
    rating: 4.4,
    reviewCount: 18,
    sold: 340,
    farmerEmail: "ravi@farmmart.io",
  },
];

export const SEED_REVIEWS = [
  { rating: 5, comment: "Excellent quality and quick delivery. Will order again!", user: "buyer@farmmart.io" },
  { rating: 4, comment: "Good product, packaging could be better.", user: "buyer@farmmart.io" },
  { rating: 5, comment: "Fresh and exactly as described. Highly recommend.", user: "wholesale@farmmart.io" },
  { rating: 5, comment: "Top-grade produce. Fair pricing for bulk buyers.", user: "wholesale@farmmart.io" },
  { rating: 4, comment: "Quality is good but shipment was a day late.", user: "buyer@farmmart.io" },
  { rating: 5, comment: "Authentic taste, reminded me of home. Five stars!", user: "buyer@farmmart.io" },
];
